### ISSUE TITLE
Problem running probav_esrgan.yml

### ISSUE THREAD

**Issue by yunseok624** [allenai/satlas-super-resolution#15]
I'm trying to run the model and I encounter some problem:

(base) [park.yunseok@gn20 satlas-super-resolution]$ python -m ssr.train -opt ssr/options/probav_esrgan.yml
/trinity/home/park.yunseok/.local/lib/python3.8/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Traceback (most recent call last):
  File "/trinity/shared/opt/python/3.8.5/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/trinity/shared/opt/python/3.8.5/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/beegfs/home/park.yunseok/satlas-super-resolution/ssr/train.py", line 182, in <module>
    train_pipeline(root_path)
  File "/beegfs/home/park.yunseok/satlas-super-resolution/ssr/train.py", line 53, in train_pipeline
    opt, args = parse_options(root_path, is_train=True)
  File "/beegfs/home/park.yunseok/satlas-super-resolution/ssr/utils/options.py", line 66, in parse_options
    opt['dist'] = False
TypeError: 'str' object does not support item assignment

**Comment by piperwolters** [comment]
Hello, I usually get that error when the specified paths to data directories are incorrect. Please check that your config file has the correct paths pointing to the data.
